[project]
name = "process-performance-indicators"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "mypy>=1.15.0",
    "pandas>=2.2.3",
    "pandera>=0.23.1",
    "ruff>=0.11.4",
]
